language: java
arch:
    - AMD64
    - ppc64le
sudo: false
jdk:
  - openjdk8
notifications:
  email:
    - info@sejda.org
cache:                                                                          
  directories:                                                                  
    - $HOME/.m2     
